
package localhost.agency.category;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CategoryService", targetNamespace = "http://localhost/agency/category", wsdlLocation = "http://localhost:8080/Sanctus-ejb/CategoryService/CategoryService?wsdl")
public class CategoryService
    extends Service
{

    private final static URL CATEGORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYSERVICE_EXCEPTION;
    private final static QName CATEGORYSERVICE_QNAME = new QName("http://localhost/agency/category", "CategoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/CategoryService/CategoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYSERVICE_WSDL_LOCATION = url;
        CATEGORYSERVICE_EXCEPTION = e;
    }

    public CategoryService() {
        super(__getWsdlLocation(), CATEGORYSERVICE_QNAME);
    }

    public CategoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYSERVICE_QNAME, features);
    }

    public CategoryService(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYSERVICE_QNAME);
    }

    public CategoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYSERVICE_QNAME, features);
    }

    public CategoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CategoryServiceRemote
     */
    @WebEndpoint(name = "CategoryServicePort")
    public CategoryServiceRemote getCategoryServicePort() {
        return super.getPort(new QName("http://localhost/agency/category", "CategoryServicePort"), CategoryServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryServiceRemote
     */
    @WebEndpoint(name = "CategoryServicePort")
    public CategoryServiceRemote getCategoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/category", "CategoryServicePort"), CategoryServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYSERVICE_EXCEPTION!= null) {
            throw CATEGORYSERVICE_EXCEPTION;
        }
        return CATEGORYSERVICE_WSDL_LOCATION;
    }

}
