
package localhost.agency.category;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.zegates.sanctus.services.remote.Category;
import com.zegates.sanctus.services.remote.CategoryArray;
import com.zegates.sanctus.services.remote.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CategoryServiceRemote", targetNamespace = "http://remote.services.sanctus.zegates.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoryServiceRemote {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.Category
     */
    @WebMethod
    @WebResult(partName = "return")
    public Category getConstructionForName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void create(
        @WebParam(name = "arg0", partName = "arg0")
        Category arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void destroy(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.CategoryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public CategoryArray findConstructionEntitiesLimit(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @return
     *     returns com.zegates.sanctus.services.remote.CategoryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public CategoryArray findConstructionEntities();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.Category
     */
    @WebMethod
    @WebResult(partName = "return")
    public Category findConstruction(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void edit(
        @WebParam(name = "arg0", partName = "arg0")
        Category arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int getConstructionCount();

}
