
package localhost.agency.supplyorderdetail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupplyOrderDetailService", targetNamespace = "http://localhost/agency/supplyorderdetail", wsdlLocation = "http://localhost:8080/Sanctus-ejb/SupplyOrderDetailService/SupplyOrderDetailService?wsdl")
public class SupplyOrderDetailService
    extends Service
{

    private final static URL SUPPLYORDERDETAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPPLYORDERDETAILSERVICE_EXCEPTION;
    private final static QName SUPPLYORDERDETAILSERVICE_QNAME = new QName("http://localhost/agency/supplyorderdetail", "SupplyOrderDetailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/SupplyOrderDetailService/SupplyOrderDetailService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPPLYORDERDETAILSERVICE_WSDL_LOCATION = url;
        SUPPLYORDERDETAILSERVICE_EXCEPTION = e;
    }

    public SupplyOrderDetailService() {
        super(__getWsdlLocation(), SUPPLYORDERDETAILSERVICE_QNAME);
    }

    public SupplyOrderDetailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPPLYORDERDETAILSERVICE_QNAME, features);
    }

    public SupplyOrderDetailService(URL wsdlLocation) {
        super(wsdlLocation, SUPPLYORDERDETAILSERVICE_QNAME);
    }

    public SupplyOrderDetailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPPLYORDERDETAILSERVICE_QNAME, features);
    }

    public SupplyOrderDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplyOrderDetailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SupplyOrderDetailServiceRemote
     */
    @WebEndpoint(name = "SupplyOrderDetailServicePort")
    public SupplyOrderDetailServiceRemote getSupplyOrderDetailServicePort() {
        return super.getPort(new QName("http://localhost/agency/supplyorderdetail", "SupplyOrderDetailServicePort"), SupplyOrderDetailServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupplyOrderDetailServiceRemote
     */
    @WebEndpoint(name = "SupplyOrderDetailServicePort")
    public SupplyOrderDetailServiceRemote getSupplyOrderDetailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/supplyorderdetail", "SupplyOrderDetailServicePort"), SupplyOrderDetailServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPPLYORDERDETAILSERVICE_EXCEPTION!= null) {
            throw SUPPLYORDERDETAILSERVICE_EXCEPTION;
        }
        return SUPPLYORDERDETAILSERVICE_WSDL_LOCATION;
    }

}
