
package localhost.agency.orderdetail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderDetailService", targetNamespace = "http://localhost/agency/orderdetail", wsdlLocation = "http://localhost:8080/Sanctus-ejb/OrderDetailService/OrderDetailService?wsdl")
public class OrderDetailService
    extends Service
{

    private final static URL ORDERDETAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERDETAILSERVICE_EXCEPTION;
    private final static QName ORDERDETAILSERVICE_QNAME = new QName("http://localhost/agency/orderdetail", "OrderDetailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/OrderDetailService/OrderDetailService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERDETAILSERVICE_WSDL_LOCATION = url;
        ORDERDETAILSERVICE_EXCEPTION = e;
    }

    public OrderDetailService() {
        super(__getWsdlLocation(), ORDERDETAILSERVICE_QNAME);
    }

    public OrderDetailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERDETAILSERVICE_QNAME, features);
    }

    public OrderDetailService(URL wsdlLocation) {
        super(wsdlLocation, ORDERDETAILSERVICE_QNAME);
    }

    public OrderDetailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERDETAILSERVICE_QNAME, features);
    }

    public OrderDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderDetailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderDetailServiceRemote
     */
    @WebEndpoint(name = "OrderDetailServicePort")
    public OrderDetailServiceRemote getOrderDetailServicePort() {
        return super.getPort(new QName("http://localhost/agency/orderdetail", "OrderDetailServicePort"), OrderDetailServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderDetailServiceRemote
     */
    @WebEndpoint(name = "OrderDetailServicePort")
    public OrderDetailServiceRemote getOrderDetailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/orderdetail", "OrderDetailServicePort"), OrderDetailServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERDETAILSERVICE_EXCEPTION!= null) {
            throw ORDERDETAILSERVICE_EXCEPTION;
        }
        return ORDERDETAILSERVICE_WSDL_LOCATION;
    }

}
