
package localhost.agency.supplierservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.zegates.sanctus.services.remote.ObjectFactory;
import com.zegates.sanctus.services.remote.Supplier;
import com.zegates.sanctus.services.remote.SupplierArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SupplierServiceRemote", targetNamespace = "http://remote.services.sanctus.zegates.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SupplierServiceRemote {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.Supplier
     */
    @WebMethod
    @WebResult(partName = "return")
    public Supplier findSupplierForName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void create(
        @WebParam(name = "arg0", partName = "arg0")
        Supplier arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void destroy(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplierArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplierArray findSupplierEntitiesLimit(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.Supplier
     */
    @WebMethod
    @WebResult(partName = "return")
    public Supplier findSupplier(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplierArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplierArray findSupplierEntities();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void edit(
        @WebParam(name = "arg0", partName = "arg0")
        Supplier arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplierArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplierArray findSuppliers(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int getSupplierCount();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplierArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplierArray findSuppliersOrder(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
