
package localhost.agency.ordersservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.zegates.sanctus.services.remote.ObjectFactory;
import com.zegates.sanctus.services.remote.Orders;
import com.zegates.sanctus.services.remote.OrdersArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrdersServiceRemote", targetNamespace = "http://remote.services.sanctus.zegates.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrdersServiceRemote {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void create(
        @WebParam(name = "arg0", partName = "arg0")
        Orders arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void destroy(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int getOrdersCount();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long getLatesOrdersID();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.OrdersArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrdersArray findOrdersEntitiesLimit(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.OrdersArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrdersArray findOrdersEntitiesPaidfalse(
        @WebParam(name = "arg0", partName = "arg0")
        boolean arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void edit(
        @WebParam(name = "arg0", partName = "arg0")
        Orders arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.Orders
     */
    @WebMethod
    @WebResult(partName = "return")
    public Orders findOrders(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns com.zegates.sanctus.services.remote.OrdersArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrdersArray findOrdersEntities();

}
