
package localhost.agency.logsession;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogSessionService", targetNamespace = "http://localhost/agency/logsession", wsdlLocation = "http://localhost:8080/Sanctus-ejb/LogSessionService/LogSessionService?wsdl")
public class LogSessionService
    extends Service
{

    private final static URL LOGSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSESSIONSERVICE_EXCEPTION;
    private final static QName LOGSESSIONSERVICE_QNAME = new QName("http://localhost/agency/logsession", "LogSessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/LogSessionService/LogSessionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSESSIONSERVICE_WSDL_LOCATION = url;
        LOGSESSIONSERVICE_EXCEPTION = e;
    }

    public LogSessionService() {
        super(__getWsdlLocation(), LOGSESSIONSERVICE_QNAME);
    }

    public LogSessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSESSIONSERVICE_QNAME, features);
    }

    public LogSessionService(URL wsdlLocation) {
        super(wsdlLocation, LOGSESSIONSERVICE_QNAME);
    }

    public LogSessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSESSIONSERVICE_QNAME, features);
    }

    public LogSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogSessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogSessionServiceRemote
     */
    @WebEndpoint(name = "LogSessionServicePort")
    public LogSessionServiceRemote getLogSessionServicePort() {
        return super.getPort(new QName("http://localhost/agency/logsession", "LogSessionServicePort"), LogSessionServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogSessionServiceRemote
     */
    @WebEndpoint(name = "LogSessionServicePort")
    public LogSessionServiceRemote getLogSessionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/logsession", "LogSessionServicePort"), LogSessionServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSESSIONSERVICE_EXCEPTION!= null) {
            throw LOGSESSIONSERVICE_EXCEPTION;
        }
        return LOGSESSIONSERVICE_WSDL_LOCATION;
    }

}
