
package localhost.agency.supplyorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupplyOrderService", targetNamespace = "http://localhost/agency/supplyorder", wsdlLocation = "http://localhost:8080/Sanctus-ejb/SupplyOrderService/SupplyOrderService?wsdl")
public class SupplyOrderService
    extends Service
{

    private final static URL SUPPLYORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPPLYORDERSERVICE_EXCEPTION;
    private final static QName SUPPLYORDERSERVICE_QNAME = new QName("http://localhost/agency/supplyorder", "SupplyOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/SupplyOrderService/SupplyOrderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPPLYORDERSERVICE_WSDL_LOCATION = url;
        SUPPLYORDERSERVICE_EXCEPTION = e;
    }

    public SupplyOrderService() {
        super(__getWsdlLocation(), SUPPLYORDERSERVICE_QNAME);
    }

    public SupplyOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPPLYORDERSERVICE_QNAME, features);
    }

    public SupplyOrderService(URL wsdlLocation) {
        super(wsdlLocation, SUPPLYORDERSERVICE_QNAME);
    }

    public SupplyOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPPLYORDERSERVICE_QNAME, features);
    }

    public SupplyOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplyOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SupplyOrderServiceRemote
     */
    @WebEndpoint(name = "SupplyOrderServicePort")
    public SupplyOrderServiceRemote getSupplyOrderServicePort() {
        return super.getPort(new QName("http://localhost/agency/supplyorder", "SupplyOrderServicePort"), SupplyOrderServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupplyOrderServiceRemote
     */
    @WebEndpoint(name = "SupplyOrderServicePort")
    public SupplyOrderServiceRemote getSupplyOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/supplyorder", "SupplyOrderServicePort"), SupplyOrderServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPPLYORDERSERVICE_EXCEPTION!= null) {
            throw SUPPLYORDERSERVICE_EXCEPTION;
        }
        return SUPPLYORDERSERVICE_WSDL_LOCATION;
    }

}
