
package localhost.agency.supplyorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.zegates.sanctus.services.remote.ObjectFactory;
import com.zegates.sanctus.services.remote.SupplyOrder;
import com.zegates.sanctus.services.remote.SupplyOrderArray;
import com.zegates.sanctus.services.remote.SupplyOrderDetailArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SupplyOrderServiceRemote", targetNamespace = "http://remote.services.sanctus.zegates.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SupplyOrderServiceRemote {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void destroy(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void create(
        @WebParam(name = "arg0", partName = "arg0")
        SupplyOrder arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplyOrder
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplyOrder findSupplyOrder(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplyOrderDetailArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplyOrderDetailArray findSupplyOrdersByLineId(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int getSupplyOrderCount();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void edit(
        @WebParam(name = "arg0", partName = "arg0")
        SupplyOrder arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplyOrderArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplyOrderArray findSupplyOrderByColumn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplyOrderArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplyOrderArray findSupplyOrderEntitiesLimit(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @return
     *     returns com.zegates.sanctus.services.remote.SupplyOrderArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public SupplyOrderArray findSupplyOrderEntities();

}
