
package localhost.agency.metric;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MetricService", targetNamespace = "http://localhost/agency/metric", wsdlLocation = "http://localhost:8080/Sanctus-ejb/MetricService/MetricService?wsdl")
public class MetricService
    extends Service
{

    private final static URL METRICSERVICE_WSDL_LOCATION;
    private final static WebServiceException METRICSERVICE_EXCEPTION;
    private final static QName METRICSERVICE_QNAME = new QName("http://localhost/agency/metric", "MetricService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/MetricService/MetricService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METRICSERVICE_WSDL_LOCATION = url;
        METRICSERVICE_EXCEPTION = e;
    }

    public MetricService() {
        super(__getWsdlLocation(), METRICSERVICE_QNAME);
    }

    public MetricService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METRICSERVICE_QNAME, features);
    }

    public MetricService(URL wsdlLocation) {
        super(wsdlLocation, METRICSERVICE_QNAME);
    }

    public MetricService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METRICSERVICE_QNAME, features);
    }

    public MetricService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetricService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetricServiceRemote
     */
    @WebEndpoint(name = "MetricServicePort")
    public MetricServiceRemote getMetricServicePort() {
        return super.getPort(new QName("http://localhost/agency/metric", "MetricServicePort"), MetricServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetricServiceRemote
     */
    @WebEndpoint(name = "MetricServicePort")
    public MetricServiceRemote getMetricServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/metric", "MetricServicePort"), MetricServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METRICSERVICE_EXCEPTION!= null) {
            throw METRICSERVICE_EXCEPTION;
        }
        return METRICSERVICE_WSDL_LOCATION;
    }

}
