
package localhost.agency.manufacturer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManufacturerService", targetNamespace = "http://localhost/agency/manufacturer", wsdlLocation = "http://localhost:8080/Sanctus-ejb/ManufacturerService/ManufacturerService?wsdl")
public class ManufacturerService
    extends Service
{

    private final static URL MANUFACTURERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANUFACTURERSERVICE_EXCEPTION;
    private final static QName MANUFACTURERSERVICE_QNAME = new QName("http://localhost/agency/manufacturer", "ManufacturerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/ManufacturerService/ManufacturerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANUFACTURERSERVICE_WSDL_LOCATION = url;
        MANUFACTURERSERVICE_EXCEPTION = e;
    }

    public ManufacturerService() {
        super(__getWsdlLocation(), MANUFACTURERSERVICE_QNAME);
    }

    public ManufacturerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANUFACTURERSERVICE_QNAME, features);
    }

    public ManufacturerService(URL wsdlLocation) {
        super(wsdlLocation, MANUFACTURERSERVICE_QNAME);
    }

    public ManufacturerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANUFACTURERSERVICE_QNAME, features);
    }

    public ManufacturerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManufacturerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManufacturerServiceRemote
     */
    @WebEndpoint(name = "ManufacturerServicePort")
    public ManufacturerServiceRemote getManufacturerServicePort() {
        return super.getPort(new QName("http://localhost/agency/manufacturer", "ManufacturerServicePort"), ManufacturerServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManufacturerServiceRemote
     */
    @WebEndpoint(name = "ManufacturerServicePort")
    public ManufacturerServiceRemote getManufacturerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/manufacturer", "ManufacturerServicePort"), ManufacturerServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANUFACTURERSERVICE_EXCEPTION!= null) {
            throw MANUFACTURERSERVICE_EXCEPTION;
        }
        return MANUFACTURERSERVICE_WSDL_LOCATION;
    }

}
