
package localhost.agency.cashtransfer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CashTransferService", targetNamespace = "http://localhost/agency/cashtransfer", wsdlLocation = "http://localhost:8080/Sanctus-ejb/CashTransferService/CashTransferService?wsdl")
public class CashTransferService
    extends Service
{

    private final static URL CASHTRANSFERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CASHTRANSFERSERVICE_EXCEPTION;
    private final static QName CASHTRANSFERSERVICE_QNAME = new QName("http://localhost/agency/cashtransfer", "CashTransferService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Sanctus-ejb/CashTransferService/CashTransferService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CASHTRANSFERSERVICE_WSDL_LOCATION = url;
        CASHTRANSFERSERVICE_EXCEPTION = e;
    }

    public CashTransferService() {
        super(__getWsdlLocation(), CASHTRANSFERSERVICE_QNAME);
    }

    public CashTransferService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CASHTRANSFERSERVICE_QNAME, features);
    }

    public CashTransferService(URL wsdlLocation) {
        super(wsdlLocation, CASHTRANSFERSERVICE_QNAME);
    }

    public CashTransferService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CASHTRANSFERSERVICE_QNAME, features);
    }

    public CashTransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CashTransferService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CashTransferServiceRemote
     */
    @WebEndpoint(name = "CashTransferServicePort")
    public CashTransferServiceRemote getCashTransferServicePort() {
        return super.getPort(new QName("http://localhost/agency/cashtransfer", "CashTransferServicePort"), CashTransferServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CashTransferServiceRemote
     */
    @WebEndpoint(name = "CashTransferServicePort")
    public CashTransferServiceRemote getCashTransferServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/agency/cashtransfer", "CashTransferServicePort"), CashTransferServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CASHTRANSFERSERVICE_EXCEPTION!= null) {
            throw CASHTRANSFERSERVICE_EXCEPTION;
        }
        return CASHTRANSFERSERVICE_WSDL_LOCATION;
    }

}
