/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agency.gui;

import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import agency.other.OtherController;
import agency.persistance.controller.LogSessionJpaController;
import agency.persistance.controller.LogUserJpaController;
import agency.persistance.controller.remote.LogUserController;
import agency.persistance.entity.LogSession;
import agency.persistance.entity.LogUser;
import agency.persistance.factory.ControllerFactory;

/**
 *
 * @author Sandaruwan
 */
public class StartSession extends javax.swing.JFrame {

    private Long uid;
    private LogUser user = null;
    private LogSessionJpaController logSessionJpaController;
    private LogUserController logUserJpaController;
    private LogSession lgs = null;

    /**
     * Creates new form StartSession
     */
    StartSession() {
        initComponents();

        setLocationRelativeTo(null);
        logSessionJpaController = ControllerFactory.getSessionJpaController();
        logUserJpaController = ControllerFactory.getLogUserJpaController();

        tblSessionDetails.requestFocus();
        tblSessionDetails.setRowSelectionAllowed(true);
    }

    public StartSession(Long uid) {
        this();
        this.uid = uid;
        user = logUserJpaController.findLogUser(uid);

        List<LogSession> logSessions = user.getLogSessions();
        if (logSessions != null) {
            String[] colNames = {"Session ID", "Date From", "Time From", "Time Till"};
            DefaultTableModel dtm = new DefaultTableModel(colNames, 0){
            
                boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

                @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

            for (int i = 0; i < logSessions.size(); i++) {
                LogSession logSession = logSessions.get(i);
                if (!logSession.isFinalised()) {
                    Calendar c = new GregorianCalendar();
                    c.setTime(logSession.getDateStarted());
                    dtm.addRow(new String[]{logSession.getSeid() + "",
                                c.get(Calendar.DAY_OF_MONTH) + "/" + c.get(Calendar.MONTH) + "/"
                                + c.get(Calendar.YEAR), logSession.getTimeStarted().toString(), null});
                }
            }
            txtName.setText(user.getName());
            tblSessionDetails.setModel(dtm);
            txtUID.setText(OtherController.formatCode("U", user.getUid(), 5));
            txtDate.setText(OtherController.getDate());
        }
//        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSessionDetails = new javax.swing.JTable();
        btnConSess = new javax.swing.JButton();
        btnNewSess = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel1.setText("Logged User");

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel2.setText("User ID");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N

        txtUID.setEditable(false);
        txtUID.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel3.setText("Date");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Previous Unfinished Session Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Droid Sans", 0, 11), java.awt.Color.black)); // NOI18N

        tblSessionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Session ID", "Date", "Time From", "Time Till"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSessionDetails.getTableHeader().setReorderingAllowed(false);
        tblSessionDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSessionDetailsMouseClicked(evt);
            }
        });
        tblSessionDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSessionDetailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSessionDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnConSess.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        btnConSess.setText("CONTINUE SESSION");
        btnConSess.setEnabled(false);
        btnConSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConSessActionPerformed(evt);
            }
        });

        btnNewSess.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        btnNewSess.setText("NEW SESSION");
        btnNewSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSessActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        btnExit.setText("EXIT");

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel4.setText("Welcome to Zegates Distribution Management System");

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel5.setText("SELECT A SESSION TO START OR CHOOSE  NEW SESSION TO START A NEW ONE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewSess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConSess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewSess)
                    .addComponent(btnConSess)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSessActionPerformed
        MainFrame mainFrame = new MainFrame(user, null);
        mainFrame.setVisible(true);
//        System.gc();
        this.dispose();
//        System.gc();
    }//GEN-LAST:event_btnNewSessActionPerformed

    private void tblSessionDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSessionDetailsMouseClicked
        int row = tblSessionDetails.getSelectedRow();
        if (row != -1) {
            try {
                lgs = logSessionJpaController.findLogSession(
                        Long.parseLong((String) tblSessionDetails.getValueAt(row, 0)));

                btnConSess.setEnabled(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error in formatting. Please restart.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tblSessionDetailsMouseClicked

    private void btnConSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConSessActionPerformed
        if (lgs != null) {
            MainFrame mainFrame = new MainFrame(user, lgs);
            mainFrame.setVisible(true);
    //        System.gc();
            this.dispose();
        }
    }//GEN-LAST:event_btnConSessActionPerformed

    private void tblSessionDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSessionDetailsKeyReleased
        tblSessionDetailsMouseClicked(null);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnConSess.doClick();
        }
    }//GEN-LAST:event_tblSessionDetailsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartSession().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConSess;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewSess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSessionDetails;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables
}
