/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agency.gui;

import com.sun.java.swing.plaf.motif.MotifBorders;
import java.awt.Font;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.border.AbstractBorder;
import javax.swing.table.DefaultTableModel;
import agency.persistance.controller.SupplierJpaController;
import agency.persistance.entity.Supplier;
import agency.persistance.factory.ControllerFactory;

/**
 *
 * @author Sandaruwan
 */
public class SuppliersFrame extends javax.swing.JInternalFrame implements Observer{

    private final SupplierJpaController sjc;
    private final DefaultTableModel dtm;
    private MainFrame mainFrame;

    /**
     * Creates new form SuppliersFrame
     */
    public SuppliersFrame(MainFrame mf) {
        initComponents();
        this.mainFrame=mf;
        sjc = ControllerFactory.getSupplierJpaController();
        setId();
        validation();
        dtm = (DefaultTableModel) tblfnd.getModel();
        chbcompanyName.doClick();
        loading();
        btnAll.doClick();
        sjc.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAddSupplier1 = new javax.swing.JButton();
        tbpMain = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCompTitle = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtCompTel = new javax.swing.JTextField();
        txtCompEmail = new javax.swing.JTextField();
        txtCEO = new javax.swing.JTextField();
        cmbCompCEOTitle = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        txtSupID = new javax.swing.JTextField();
        txtASDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chbLocation = new javax.swing.JCheckBox();
        txtSearch = new javax.swing.JTextField();
        chbcompanyName = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblfnd = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        labelerror = new javax.swing.JLabel();
        btnAll = new javax.swing.JToggleButton();

        btnAddSupplier1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddSupplier1.setText("ADD SUPPLIER");
        btnAddSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplier1ActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Supplier Details");
        setToolTipText("Browse for Suppliers");

        tbpMain.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Droid Sans", 1, 10))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Name Of the Company");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Location (Address)");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setText("Telephone");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setText("Email");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setText("Name Of CEO");

        txtCompTitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCompTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompTitleKeyReleased(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLocationKeyReleased(evt);
            }
        });

        txtCompTel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCompTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompTelKeyReleased(evt);
            }
        });

        txtCompEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCompEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompEmailKeyReleased(evt);
            }
        });

        txtCEO.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCEO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEOKeyReleased(evt);
            }
        });

        cmbCompCEOTitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbCompCEOTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Miss" }));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setText("Supplier ID");

        txtSupID.setEditable(false);
        txtSupID.setBackground(new java.awt.Color(255, 186, 0));
        txtSupID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSupID.setForeground(new java.awt.Color(255, 255, 255));
        txtSupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupIDActionPerformed(evt);
            }
        });

        txtASDate.setEditable(false);
        txtASDate.setBackground(new java.awt.Color(204, 204, 204));
        txtASDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtASDate.setFocusable(false);
        txtASDate.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Date");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCompTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtSupID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtASDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cmbCompCEOTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCEO, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                            .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                            .addComponent(txtCompTel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtASDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(txtSupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCompTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCompTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCompEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCompCEOTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAddSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddSupplier.setText("ADD SUPPLIER");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupplier)
                    .addComponent(jButton1))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        tbpMain.addTab("Add Supplier", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        chbLocation.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(chbLocation);
        chbLocation.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        chbLocation.setText("By Location ");
        chbLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbLocationMouseClicked(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        chbcompanyName.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(chbcompanyName);
        chbcompanyName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        chbcompanyName.setText("By Company ");
        chbcompanyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbcompanyNameMouseClicked(evt);
            }
        });
        chbcompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbcompanyNameActionPerformed(evt);
            }
        });

        tblfnd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblfnd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suppplier ID", "Company Name", "CEO", "Locaton", "Telephone No", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblfnd.setRowHeight(20);
        tblfnd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblfnd.getTableHeader().setReorderingAllowed(false);
        tblfnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfndMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblfnd);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setText("Search:");

        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchLabel.setText("Search By");

        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton2.setText("EXIT");

        labelerror.setFont(new java.awt.Font("Droid Sans", 2, 12)); // NOI18N
        labelerror.setForeground(new java.awt.Color(204, 0, 0));

        btnAll.setText("Show All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(searchLabel)
                                .addGap(18, 18, 18)
                                .addComponent(chbcompanyName)
                                .addGap(18, 18, 18)
                                .addComponent(chbLocation)
                                .addGap(18, 18, 18)
                                .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelerror, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(chbcompanyName)
                    .addComponent(chbLocation)
                    .addComponent(btnAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelerror))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(6, 6, 6))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelerror, txtSearch});

        tbpMain.addTab("Find Supplier", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompTitleKeyReleased
        validation();
    }//GEN-LAST:event_txtCompTitleKeyReleased

    private void txtLocationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocationKeyReleased
        validation();
    }//GEN-LAST:event_txtLocationKeyReleased

    private void txtCompTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompTelKeyReleased
        validation();
    }//GEN-LAST:event_txtCompTelKeyReleased

    private void txtCEOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEOKeyReleased
        validation();
    }//GEN-LAST:event_txtCEOKeyReleased

    /**
     *
     * Creates a new supplier instance and insert the new instance to the
     * database
     *
     * @param evt Action Event for the button
     */
    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        try {
            Supplier supplier = new Supplier();
            supplier.setAddress(txtLocation.getText());
            supplier.setCompName(txtCompTitle.getText());
            supplier.setEmail(txtCompEmail.getText());
            supplier.setDateAdded(new Date(Calendar.getInstance().getTimeInMillis()));
            supplier.setSuid(Long.parseLong(txtSupID.getText()));
            supplier.setName(txtCEO.getText());
            supplier.setTimeAdded(new Time(Calendar.getInstance().getTimeInMillis()));
            supplier.setTpno(txtCompTel.getText());
            sjc.create(supplier);
            sjc.setChanged();
            sjc.notifyObservers("supplierAdded");
            btnAll.doClick();
            btnAll.doClick();
            JOptionPane.showMessageDialog(this, "Supplier Inserted Successfully", "Insert Record", JOptionPane.INFORMATION_MESSAGE);
            setId();
            clear();
    //        System.gc();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error occured in adding .\n"
                                    + ex.getMessage(), "ClassNotFound Error", JOptionPane.ERROR_MESSAGE);
    //        System.gc();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error occured in adding .\n"
                                    + ex.getMessage(), "Remote SQL Error", JOptionPane.ERROR_MESSAGE);
    //        System.gc();
        }
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void chbLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbLocationMouseClicked

        if (btnAll.isSelected() && chbLocation.isSelected()) {
            setTable("address");
        } else if (btnAll.isSelected() && chbcompanyName.isSelected()) {
            setTable("compName");
        } else {
            txtSearchKeyReleased(null);
        }
    }//GEN-LAST:event_chbLocationMouseClicked

    private void chbcompanyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbcompanyNameMouseClicked

        if (btnAll.isSelected() && chbLocation.isSelected()) {
            setTable("address");
        } else if (btnAll.isSelected() && chbcompanyName.isSelected()) {
            setTable("compName");
        } else {
            txtSearchKeyReleased(null);
        }
//        System.gc();
    }//GEN-LAST:event_chbcompanyNameMouseClicked

    private void txtSupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupIDActionPerformed

    private void txtCompEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompEmailKeyReleased
        validation();
    }//GEN-LAST:event_txtCompEmailKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String args;
        if (chbcompanyName.isSelected()) {
            args = "compName";
        } else {
            args = "address";
        }
        String queryPass = txtSearch.getText();
        if (!"".equals(queryPass)) {
            List<Supplier> suppliers = sjc.findSuppliers(queryPass, args);
            dtm.setRowCount(0);
            for (Supplier supplier : suppliers) {
                dtm.addRow(new Object[]{supplier.getSuid(), supplier.getCompName(),
                            supplier.getName(), supplier.getAddress(), supplier.getTpno(), supplier.getEmail()});
            }
            if (suppliers.isEmpty()) {
                labelerror.setText("No Such Supplier");
                labelerror.setFont(new Font("DroidSans", Font.ITALIC, 12));
            } else {
                labelerror.setText("");
            }
        }
//        System.gc();
    }//GEN-LAST:event_txtSearchKeyReleased

    public JTabbedPane getTbpMain() {
        return tbpMain;
    }

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tblfndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfndMouseClicked
        if (evt.getClickCount() == 2) {
            Object[] objects = new Object[tblfnd.getColumnCount()];
            int selectedRow = tblfnd.getSelectedRow();
            for (int i = 0; i < tblfnd.getColumnCount(); i++) {
                objects[i] = tblfnd.getValueAt(selectedRow, i);
            }
            UpdateSupplierFrame updateSupplierFrame = new UpdateSupplierFrame(null, true, objects);
            updateSupplierFrame.setVisible(true);
        }
//        System.gc();
    }//GEN-LAST:event_tblfndMouseClicked

    private void btnAddSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSupplier1ActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        if (btnAll.isSelected()) {
            if (chbLocation.isSelected()) {
                setTable("address");
            } else {
                setTable("compName");
            }
            txtSearch.setEnabled(false);
            searchLabel.setText("Sort By");
        } else {
            dtm.setRowCount(0);
            txtSearch.setEnabled(true);
            searchLabel.setText("Search By");
        }
//        System.gc();
    }//GEN-LAST:event_btnAllActionPerformed

    private void chbcompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbcompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbcompanyNameActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnAddSupplier1;
    private javax.swing.JToggleButton btnAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbLocation;
    private javax.swing.JCheckBox chbcompanyName;
    private javax.swing.JComboBox cmbCompCEOTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelerror;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTable tblfnd;
    private javax.swing.JTabbedPane tbpMain;
    private javax.swing.JTextField txtASDate;
    private javax.swing.JTextField txtCEO;
    private javax.swing.JTextField txtCompEmail;
    private javax.swing.JTextField txtCompTel;
    private javax.swing.JTextField txtCompTitle;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupID;
    // End of variables declaration//GEN-END:variables

    private void setId() {
        txtSupID.setText((sjc.getSupplierCount() + 1) + "");
        DateFormat dfD = new SimpleDateFormat("yyyy-MM-dd hh:mm:aa");
        txtASDate.setText(dfD.format(Calendar.getInstance().getTimeInMillis()));
//        System.gc();

    }

    private void clear() {
        txtCEO.setText("");
        txtCompEmail.setText("");
        txtCompTel.setText("");
        txtCompTitle.setText("");
        txtSearch.setText("");
        txtLocation.setText("");
//        System.gc();
    }

    private void validation() {
        if (!"".equals(txtCEO.getText()) && !"".equals(txtLocation.getText()) && !"".equals(txtCompTel.getText()) && !"".equals(txtCompTitle.getText())) {
            btnAddSupplier.setEnabled(true);
        } else {
            btnAddSupplier.setEnabled(false);
        }
//        System.gc();
    }

    private void setTable(String args) {
        List<Supplier> suppliers = sjc.findSuppliers(args);
        dtm.setRowCount(0);
        for (Supplier supplier : suppliers) {
            if (supplier.getSuid() != -1) {
                dtm.addRow(new Object[]{supplier.getSuid(), supplier.getCompName(),
                            supplier.getName(), supplier.getAddress(), supplier.getTpno(), supplier.getEmail()});
            }
        }
        txtSearch.setText("");
        labelerror.setText("");
//        System.gc();
    }

    /**
     * This method invokes because of persistence is slowing on the new instance
     * of the application
     *
     *
     */
    private void loading() {
        txtSearch.setText("!");
        txtSearchKeyReleased(null);
//        System.gc();
    }

    @Override
    public void update(Observable o, Object arg) {
        mainFrame.update(o, "supplierAdded");
//        System.gc();
    }
}
