/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agency.gui;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import agency.persistance.controller.ItemJpaController;
import agency.persistance.controller.SupplyOrderDetailJpaController;
import agency.persistance.controller.exceptions.NonexistentEntityException;
import agency.persistance.entity.Item;
import agency.persistance.entity.SupplyOrderDetail;
import agency.persistance.factory.ControllerFactory;

/**
 *
 * @author Thilina
 */
public class UpdateSupplyOrderDetail extends javax.swing.JDialog {

    private final SupplyOrderDetailJpaController sodjc;
    private final ItemJpaController ijc;
    private final long iid;
    private final int qty;
    private final int rqty;

    /**
     * Creates new form UpdateSupplyOrderDetail
     */
    UpdateSupplyOrderDetail(java.awt.Frame parent, boolean modal, Object[] objects) {
        super(parent, modal);
        initComponents();
        txtDeatialID.setText(objects[0] + "");
        iid = (Long) objects[1];
        txtQuantity.setText(objects[2] + "");
        qty = (int) objects[2];
        txtRQuantity.setText(objects[3] + "");
        rqty = (int) objects[3];
        txtBuyingprice.setText(objects[4] + "");
        txtSellingPrice.setText(objects[5] + "");
        sodjc = ControllerFactory.getSupplyOrderDetailJpaController();
        ijc = ControllerFactory.getItemJpaController();
        validation();
        setId();
        setLocationRelativeTo(null);
//        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtBuyingprice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDeatialID = new javax.swing.JTextField();
        btnUpdateDetail = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        cmbItemName = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        txtRQuantity = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtSellingPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Supply Order Detail");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Supply Order Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Droid Sans", 1, 10))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Item Name");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Quantity");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setText("Buying Price");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        txtBuyingprice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtBuyingprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuyingpriceKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setText("Detail ID");

        txtDeatialID.setEditable(false);
        txtDeatialID.setBackground(new java.awt.Color(255, 186, 0));
        txtDeatialID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDeatialID.setForeground(new java.awt.Color(255, 255, 255));
        txtDeatialID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeatialIDActionPerformed(evt);
            }
        });

        btnUpdateDetail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnUpdateDetail.setText("UPDATE DETAIL");
        btnUpdateDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDetailActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cmbItemName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbItemName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tyre 4 Wheelers 205/55 R" }));
        cmbItemName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemNameItemStateChanged(evt);
            }
        });
        cmbItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemNamejComboBox6ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Remaining Quantity");

        txtRQuantity.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtRQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRQuantityKeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setText("Buying Price");

        txtSellingPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSellingPriceKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeatialID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuyingprice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel19, jLabel20, jLabel28});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBuyingprice, txtDeatialID, txtQuantity, txtRQuantity, txtSellingPrice});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDeatialID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtRQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBuyingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateDetail)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbItemName, jLabel17, jLabel19, jLabel20, jLabel28, txtBuyingprice, txtDeatialID, txtQuantity});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        if (!"".equals(txtQuantity.getText())) {
            int quantity = Integer.parseInt(txtQuantity.getText());
            int rquantity = rqty + quantity - qty;
            if (rquantity < 0) {
                txtRQuantity.setText("");
            } else {
                txtRQuantity.setText(rquantity + "");
            }
        } else {
            txtQuantity.setText(qty + "");
            txtRQuantity.setText(rqty + "");
        }
        validation();
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtBuyingpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuyingpriceKeyReleased
        validation();
    }//GEN-LAST:event_txtBuyingpriceKeyReleased

    private void txtDeatialIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeatialIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeatialIDActionPerformed

    private void btnUpdateDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDetailActionPerformed
        try {

            String itemName = (String) cmbItemName.getSelectedItem();
            String[] split = itemName.split(" -- ");
            Item item = ijc.findItem(Long.parseLong(split[0]));
            SupplyOrderDetail detail = sodjc.findSupplyOrderDetail(Long.parseLong(txtDeatialID.getText()));
            if (detail != null) {
                //detail.setSodid();
                detail.setItem(item);
                detail.setQty(Integer.parseInt(txtQuantity.getText()));
                detail.setRemainingQty(Integer.parseInt(txtRQuantity.getText()));
                detail.setBuyingPrice(Double.parseDouble(txtBuyingprice.getText()));
                detail.setSellingPrice(Double.parseDouble(txtSellingPrice.getText()));
                int conf = JOptionPane.showConfirmDialog(null, "are you sure these values "
                        + "are correct?", "Confirm", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (conf == 0) {
                    sodjc.edit(detail);
                    JOptionPane.showMessageDialog(this, "Order Detail Updated Successfully", "Update Record", JOptionPane.INFORMATION_MESSAGE);
                    setId();
                }
            } else {
        //        System.gc();
                throw new Exception("Supply Detail was null.. ");
            }
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(this, "Error in updating "
                    + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(UpdateSupplyOrderDetail.class.getName()).log(Level.SEVERE, null, ex);
    //        System.gc();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error in updating "
                    + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(UpdateSupplyOrderDetail.class.getName()).log(Level.SEVERE, null, ex);
    //        System.gc();
        }
//        System.gc();
    }//GEN-LAST:event_btnUpdateDetailActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbItemNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemNameItemStateChanged
    }//GEN-LAST:event_cmbItemNameItemStateChanged

    private void cmbItemNamejComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemNamejComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemNamejComboBox6ActionPerformed

    private void txtRQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQuantityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRQuantityKeyReleased

    private void txtSellingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellingPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdateDetail;
    private javax.swing.JComboBox cmbItemName;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtBuyingprice;
    private javax.swing.JTextField txtDeatialID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRQuantity;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables

    private void validation() {
        if (cmbItemName.getSelectedIndex() != -1 && !"".equals(txtRQuantity.getText()) && !"".equals(txtQuantity.getText()) && !"".equals(txtBuyingprice.getText()) && !"".equals(txtSellingPrice.getText())) {
            btnUpdateDetail.setEnabled(true);
        } else {
            btnUpdateDetail.setEnabled(false);
        }
    }

    private void setId() {
        List<Item> items = ijc.findItemEntities();
        String selected = null;
        cmbItemName.removeAllItems();
        for (Item item : items) {
            String itemName = item.getIid() + " -- " + item.getManufacturer().getName() + " " + item.getName();
            if (item.getIid() == iid) {
                selected = itemName;
            }
            cmbItemName.addItem(itemName);
        }
        if (selected != null) {
            cmbItemName.setSelectedItem(selected);
        }
    }
}
