/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agency.gui;

import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import agency.other.OtherController;
import agency.persistance.controller.remote.ItemController;
import agency.persistance.controller.remote.ManufacturerController;

import agency.persistance.factory.ControllerFactory;
import com.zegates.sanctus.services.remote.Category;
import com.zegates.sanctus.services.remote.Item;
import com.zegates.sanctus.services.remote.Manufacturer;
import com.zegates.sanctus.services.remote.Metric;

/**
 *
 * @author Gayath
 */
public class UpdateItemFrame extends javax.swing.JDialog {

    /**
     * Creates new form UpdateItemFrame
     */
    private ManufacturerController mjc;
    private ItemController ijc;
    private String itemCode;

    public UpdateItemFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    UpdateItemFrame(java.awt.Frame parent, boolean b, String valueAt) {
        this(parent, b);
        this.itemCode = valueAt;

        mjc = ControllerFactory.getManufacturerController();
        ijc = ControllerFactory.getItemController();
        /**
         * Refresh values of combo boxes
         */
        refreshConstructions();
        refreshManufacturers();
        refreshCategories();
        /**
         * Find and sets values of the updating item
         */
        evaluateValues();
//        System.gc();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtItemCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbManufacturer = new javax.swing.JComboBox();
        btnAddManufacturer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbMetric = new javax.swing.JComboBox();
        btnAddConstruction = new javax.swing.JButton();
        btnUpdateSupplier = new javax.swing.JButton();
        btnAddSupplier1 = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Find Item"));

        txtItemCode.setEditable(false);
        txtItemCode.setBackground(new java.awt.Color(99, 144, 177));
        txtItemCode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtItemCode.setText("I00001");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Item Code");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Item Name");

        txtItemName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Manufacturer");

        cmbManufacturer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbManufacturer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good Year" }));

        btnAddManufacturer.setText("Add Manufacturer");
        btnAddManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddManufacturerActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Metric");

        cmbMetric.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbMetric.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Radial" }));

        btnAddConstruction.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddConstruction.setText("Add Metric");
        btnAddConstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConstructionActionPerformed(evt);
            }
        });

        btnUpdateSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnUpdateSupplier.setText("UPDATE ITEM");
        btnUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplierActionPerformed(evt);
            }
        });

        btnAddSupplier1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddSupplier1.setText("EXIT");
        btnAddSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplier1ActionPerformed(evt);
            }
        });

        cmbCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tire", "Tube", "Alloy_Wheel", "Other_Retail" }));
        cmbCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbCategoryKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Category");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbMetric, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbManufacturer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAddConstruction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbMetric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddConstruction)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateSupplier)
                    .addComponent(btnAddSupplier1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddManufacturerActionPerformed
        new AddManufactureFrame(null, true).setVisible(true);
        refreshManufacturers();
//        System.gc();
    }//GEN-LAST:event_btnAddManufacturerActionPerformed

    private void btnAddConstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConstructionActionPerformed
        new AddMetricFrame(null, true).setVisible(true);
        refreshConstructions();
//        System.gc();
    }//GEN-LAST:event_btnAddConstructionActionPerformed

    private void btnUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "Are sure to update these values?",
                "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (conf == 0) {
            try {
                Long itemID = OtherController.stripOutItemCode(itemCode);
                Item item = ijc.findItem(itemID);

                Metric metric = cjc.getConstructionForName((String) cmbMetric.getSelectedItem());
                Manufacturer manufacturer = mjc.findManufacturerForName((String) cmbManufacturer.getSelectedItem());
                Category category = (Category) cmbCategory.getSelectedItem();

                item.setMetric(metric);
                item.setManufacturer(manufacturer);
                item.setName(txtItemName.getText());
                item.setCategory(category);

                ijc.edit(item);
                JOptionPane.showMessageDialog(null, "Sucessfully Updated \n"
                        + item.getName(), "Successful", JOptionPane.INFORMATION_MESSAGE);
                ijc.setChanged();
                ijc.notifyObservers("addItem");
        //        System.gc();
                this.dispose();
        //        System.gc();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error occured in\n"
                        + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
             //   Logger.getLogger(UpdateItemFrame.class.getName()).log(Level.SEVERE, null, e);
        //        System.gc();
            }
        }


    }//GEN-LAST:event_btnUpdateSupplierActionPerformed

    private void btnAddSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplier1ActionPerformed
        this.dispose();
//        System.gc();
    }//GEN-LAST:event_btnAddSupplier1ActionPerformed

    private void cmbCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCategoryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateItemFrame dialog = new UpdateItemFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddConstruction;
    private javax.swing.JButton btnAddManufacturer;
    private javax.swing.JButton btnAddSupplier1;
    private javax.swing.JButton btnUpdateSupplier;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbManufacturer;
    private javax.swing.JComboBox cmbMetric;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables

    private void refreshConstructions() {
        cmbMetric.removeAllItems();
        List<Metric> constructions = cjc.findConstructionEntities();
        for (Metric construction : constructions) {
            cmbMetric.addItem(construction.getName());
        }
//        System.gc();
    }

    private void refreshManufacturers() {
        cmbManufacturer.removeAllItems();
        List<Manufacturer> manufacturers = mjc.findManufacturerEntities();
        Collections.sort(manufacturers);
        for (Manufacturer manufacturer : manufacturers) {
            cmbManufacturer.addItem(manufacturer.getName());
        }
//        System.gc();
    }

   

    private void refreshCategories() {
        cmbCategory.removeAllItems();
//        System.gc();
    }

    private void evaluateValues() {
        Long itemID = OtherController.stripOutItemCode(itemCode);
        Item item = ijc.findItem(itemID);
        if (item == null) {
            JOptionPane.showMessageDialog(null, "Error occured in\n selecting item"
                    + "from the database", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

        txtItemCode.setText(OtherController.formatCode("I", item.getIid(), 8));
        txtItemName.setText(item.getName());
        cmbCategory.setSelectedItem(item.getCategory());
        cmbMetric.setSelectedItem(item.getMetric().getName());
        cmbManufacturer.setSelectedItem(item.getManufacturer().getName());
        
//        System.gc();
    }
}
