/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agency.gui;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import agency.other.OtherController;
import agency.persistance.controller.OrdersJpaController;
import agency.persistance.controller.SupplyOrderDetailJpaController;
import agency.persistance.controller.exceptions.NonexistentEntityException;
import agency.persistance.entity.OrderDetail;
import agency.persistance.entity.Orders;
import agency.persistance.entity.SupplyOrderDetail;
import agency.persistance.factory.ControllerFactory;

/**
 *
 * @author Sandaruwan
 */
public class ViewOrder extends javax.swing.JDialog {

    private OrdersJpaController ojc;
    private SupplyOrderDetailJpaController sodjc;
    private DefaultTableModel dtm;

    /**
     * Creates new form ViewOrder
     */
    public ViewOrder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ojc = ControllerFactory.getOrdersJpaController();
        sodjc = ControllerFactory.getSupplyOrderDetailJpaController();
        dtm = (DefaultTableModel) tblorderDetail.getModel();
        btnDoPayment.setEnabled(false);
        btnDeleteOrder.setEnabled(false);
        btnPrintOrder.setEnabled(false);
//        System.gc();
        txtID.setEditable(true);
    }

    /**
     *
     * @param parent
     * @param modal
     * @param oid
     */
    public ViewOrder(java.awt.Frame parent, boolean modal, long oid) {
        super(parent, modal);
        initComponents();
        ojc = ControllerFactory.getOrdersJpaController();
        sodjc = ControllerFactory.getSupplyOrderDetailJpaController();
        dtm = (DefaultTableModel) tblorderDetail.getModel();
        txtID.setText(oid + "");
        btnDoPayment.setEnabled(false);
        btnDeleteOrder.setEnabled(false);
        txtIDActionPerformed(null);

//        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTPNo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalBill = new javax.swing.JTextField();
        txtDue = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnDoPayment = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        btnPrintOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorderDetail = new javax.swing.JTable();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Orders");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Order ID");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Date");

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtTime.setEditable(false);
        txtTime.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Time");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Name");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        txtAddres.setEditable(false);
        txtAddres.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddresActionPerformed(evt);
            }
        });

        jLabel7.setText("Tel");

        txtTPNo.setEditable(false);
        txtTPNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Details"));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Discount");

        txtDiscount.setEditable(false);
        txtDiscount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Total Bill");

        txtTotalBill.setEditable(false);
        txtTotalBill.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtDue.setEditable(false);
        txtDue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Due");

        btnDoPayment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDoPayment.setText("DO PAYMENTS");
        btnDoPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoPaymentActionPerformed(evt);
            }
        });

        btnDeleteOrder.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnDeleteOrder.setText("DELETE ORDER");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        btnPrintOrder.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnPrintOrder.setText("PRINT ORDER");
        btnPrintOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDoPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrintOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteOrder)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiscount, txtTotalBill});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoPayment)
                    .addComponent(btnDeleteOrder)
                    .addComponent(btnPrintOrder))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblorderDetail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblorderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Supply ID", "Quantity", "Selling Price", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblorderDetail.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblorderDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(txtTPNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDate, txtID, txtTime});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        String idTxt = txtID.getText();
        if (!"".equals(idTxt)) {
            try {
                long id = Long.parseLong(idTxt);
                Orders found = ojc.findOrders(id);
                System.out.println("awa");
                if (found != null) {
                    txtDate.setText(found.getDateAdded().toString());
                    txtTime.setText(found.getTimeAdded().toString());
                    txtName.setText(found.getCustName());
                    txtAddres.setText(found.getAddress());
                    txtTPNo.setText(found.getTpNo());
                    txtTotal.setText(found.getTotal() + "");
                    txtDiscount.setText(found.getDiscount() + "");
                    txtTotalBill.setText((found.getTotal() - found.getDiscount()) + "");
                    txtDue.setText((found.getTotal() - found.getPaidAmount() - found.getDiscount()) + "");
                    List<OrderDetail> orderDetails = found.getOrderDetails();
                    dtm.setRowCount(0);
                    for (OrderDetail detail : orderDetails) {
                        dtm.addRow(new Object[]{detail.getSupplyOrderDetail().getItem().getIid(), detail.getSupplyOrderDetail().getItem().getName(), detail.getSupplyOrderDetail().getSupplyOrder().getSoid(), detail.getQty(), detail.getUnitPrice(), detail.getQty() * detail.getUnitPrice()});
                    }
                    if (found.isPaid()) {
                        btnDoPayment.setEnabled(false);
                    } else {
                        btnDoPayment.setEnabled(true);
                    }
                    btnDeleteOrder.setEnabled(true);
                    btnPrintOrder.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter valid Order ID");
                    btnDeleteOrder.setEnabled(false);
                }
            } catch (NumberFormatException ex) {
                txtID.setText("");
                JOptionPane.showMessageDialog(this, "Please enter valid Order ID");
                btnDeleteOrder.setEnabled(false);
            }
        }
//        System.gc();
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtAddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddresActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
    }//GEN-LAST:event_txtIDKeyReleased

    private void btnDoPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoPaymentActionPerformed
        long id = Long.parseLong(txtID.getText());
        new DoPaymentForm(null, true, id).setVisible(true);
    }//GEN-LAST:event_btnDoPaymentActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        Orders orders = ojc.findOrders(Long.parseLong(txtID.getText()));
        if (orders != null) {
            try {
                int conf = JOptionPane.showConfirmDialog(null, "Do you really want to delete this order?", "Confirm",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (conf == 0) {
                    List<OrderDetail> orderDetails = orders.getOrderDetails();
                    for (int i = 0; i < orderDetails.size(); i++) {
                        OrderDetail orderDetail = orderDetails.get(i);
                        SupplyOrderDetail supplyOrderDetail = orderDetail.getSupplyOrderDetail();
                        supplyOrderDetail.setRemainingQty(supplyOrderDetail.getRemainingQty() + orderDetail.getQty());
                        sodjc.edit(supplyOrderDetail);
                    }

                    ojc.destroy(orders.getOid());

                    JOptionPane.showMessageDialog(this, "Successfully Deleted", "Successful", JOptionPane.INFORMATION_MESSAGE);
                    ojc.setChanged();
                    ojc.notifyObservers("addOrder");
                    this.dispose();
                }
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "Error with the order informations\n"
                        + "Couldnot perform the operation\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error with the order\n"
                        + "\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        //        System.gc();
            }
        }
//        System.gc();
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnPrintOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintOrderActionPerformed
        JRTableModelDataSource jrt = new JRTableModelDataSource(dtm);
        String repSource = "./src/tireshop/reports/OrderPosBill.jrxml";
        Map<String, Object> param = new HashMap<String, Object>();


        param.put("Date", txtDate.getText());
        param.put("CustName", txtName.getText());
        param.put("Time", txtTime.getText());
        try {
            param.put("Orderid",
                    OtherController.formatCode("OD", Long.parseLong(txtID.getText()), 8));
            param.put("Total", txtTotalBill.getText());

            param.put("Discount", txtDiscount.getText());
            double ttbill = Double.parseDouble(txtTotalBill.getText());
            double ttDue = Double.parseDouble(txtDue.getText());

            param.put("Paid", OtherController.formatPrice(ttbill - ttDue));
            param.put("Balance", txtDue.getText());

            param.put("VehicleNo", "**********");

            JasperReport jr;
            try {
                jr = JasperCompileManager.compileReport(repSource);
                JasperPrint jp = JasperFillManager.fillReport(jr, param, jrt);

                //JasperViewer.viewReport(jp, false);
                try {
                    JasperPrintManager.printReport(jp, false);
                } catch (JRException ee) {
                    JOptionPane.showMessageDialog(null, "Printer not found ",
                            "Printer Error", JOptionPane.ERROR_MESSAGE);
                    JasperViewer.viewReport(jp, false);
                } catch (Exception ee) {
                    JOptionPane.showMessageDialog(null, "Cannot be prited ",
                            "Printer Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (JRException ex) {
                Logger.getLogger(ViewOrder.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (NumberFormatException s) {
        }
    }//GEN-LAST:event_btnPrintOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewOrder dialog = new ViewOrder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnDoPayment;
    private javax.swing.JButton btnPrintOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblorderDetail;
    private javax.swing.JTextField txtAddres;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTPNo;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalBill;
    // End of variables declaration//GEN-END:variables
}
